const http = require('http');

const NOCODB_HOST = "srv821341.hstgr.cloud";
const NOCODB_PORT = 8086;
const NOCODB_TOKEN = "nc_pat_6hZw4JgAjaFFfNbC7ui1IP4nuCi1mWWWq816JqFs";
const TABLE_ID = "mo1b63dokvbmjyg"; // menu_Items

const items = [
  // ================= 1. SPECIAL FOOD (BREAKFAST & MAINS) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "egg_avocado_croissant",
    name_en: "Egg & Avocado Croissant Sandwich",
    name_ar: "ساندوتش كرواسون البيض والأفوكادو",
    name_fr: "Croissant Sandwich Œuf & Avocat",
    description_en: "Fresh buttery croissant filled with scrambled eggs, creamy avocado slices, and microgreens. Best Seller.",
    description_ar: "كرواسون طازج بالزبدة محشو بالبيض المخفوق مع شرائح الأفوكادو الطازجة. الأكثر مبيعاً.",
    description_fr: "Croissant pur beurre garni d'œufs brouillés et tranches d'avocat frais. Meilleure vente.",
    price: 25,
    calories: 460,
    image_url: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "egg_avocado_toast",
    name_en: "Egg & Avocado Toast",
    name_ar: "توست البيض والأفوكادو",
    name_fr: "Toast Avocat & Œuf au Plat",
    description_en: "Toasted artisanal sourdough with smashed seasoned avocado and sunny-side-up eggs. Best Seller.",
    description_ar: "خبز توست محمص مع الأفوكادو المتبل والبيض المقلي الشهي. الأكثر مبيعاً.",
    description_fr: "Pain au levain toasté, écrasé d'avocat assaisonné et œufs au plat. Meilleure vente.",
    price: 25,
    calories: 420,
    image_url: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "sandwiches",
    item_id: "tunacado_sandwich",
    name_en: "Tunacado Sandwich",
    name_ar: "ساندوتش التونة توناكادو",
    name_fr: "Sandwich Tunacado",
    description_en: "Crispy grilled flatbread sandwich with whipped tuna mousse, fresh avocado, tomato, and pesto. Best Seller.",
    description_ar: "ساندوتش مقرمش محشو بموس التونة الشهي مع الأفوكادو والطماطم وصلصة البيستو. الأكثر مبيعاً.",
    description_fr: "Pain croustillant garni de mousse de thon, avocat frais, tomate et pesto. Meilleure vente.",
    price: 25,
    calories: 480,
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "omelette_cheese_croissant",
    name_en: "Omelette & Cheese Croissant",
    name_ar: "كرواسون أومليت بالجبن",
    name_fr: "Croissant Omelette & Fromage Fondant",
    description_en: "Flaky warm croissant stuffed with fluffy cheese omelette.",
    description_ar: "كرواسون دافئ وهش محشو بأومليت الجبن اللذيذ.",
    description_fr: "Croissant chaud feuilleté garni d'une omelette moelleuse au fromage.",
    price: 25,
    calories: 490,
    image_url: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "crispy_croffles",
    name_en: "Crispy Croffles Trio",
    name_ar: "كروفل مقرمش مشكل",
    name_fr: "Croffles Croustillants Gourmands",
    description_en: "Three golden pressed croissant-waffles topped with chocolate, berries, and whipped cream.",
    description_ar: "ثلاث قطع كروفل ذهبية مقرمشة مغطاة بالشوكولاتة والتوت والكراميل.",
    description_fr: "Trois croffles dorés croustillants garnis de chocolat, fruits rouges et chantilly.",
    price: 25,
    calories: 520,
    image_url: "https://images.unsplash.com/photo-1562376552-0d160a2f238d?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "bos_big_platter",
    name_en: "Bo's Big Platter",
    name_ar: "طبق بو الكبير المتكامل",
    name_fr: "Grand Plateau Petit-Déjeuner Bo's",
    description_en: "Signature hearty breakfast with scrambled eggs, sausages, baked beans, toast, and grilled hashbrown.",
    description_ar: "فطور بو الكامل والمميز: بيض مخفوق، نقانق، فاصولياء مطبوخة، توست مقرمش وبطاطس هاش براون.",
    description_fr: "Assiette complète signature : œufs brouillés, saucisses, haricots blancs, toasts et pommes rissolées.",
    price: 35,
    calories: 780,
    image_url: "https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "fluffy_pancake",
    name_en: "Fluffy Pancake Stack",
    name_ar: "فلافي بان كيك",
    name_fr: "Pancakes Moelleux & Sirop",
    description_en: "Stack of thick, golden fluffy pancakes served with pure maple syrup and butter.",
    description_ar: "طبقات من البان كيك الهش والذهبي مع شراب القيقب الأصلي والزبدة.",
    description_fr: "Pancakes moelleux et dorés servis avec sirop d'érable et beurre frais.",
    price: 25,
    calories: 540,
    image_url: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "three_cheese_omelette",
    name_en: "Three Cheese Omelette",
    name_ar: "أومليت ثلاثة أجبان",
    name_fr: "Omelette Trois Fromages",
    description_en: "Fluffy folded omelette loaded with melted cheddar, mozzarella, and parmesan, served with toast and side salad.",
    description_ar: "أومليت هش محشو بمزيج الشيدر، الموزاريلا والبارميزان مع توست محمص وسلطة جانبية.",
    description_fr: "Omelette fondante garnie de cheddar, mozzarella et parmesan, accompagnée de toasts.",
    price: 25,
    calories: 480,
    image_url: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "special_food",
    item_id: "wild_mushroom_omelette",
    name_en: "Wild Mushroom Omelette",
    name_ar: "أومليت الفطر البري",
    name_fr: "Omelette aux Champignons Sauvages",
    description_en: "Sautéed wild mushrooms and fresh herbs folded into fluffy farm-fresh eggs.",
    description_ar: "أومليت غني بقطع الفطر البري السوتيه مع الأعشاب العطرية الطازجة وتوست محمص.",
    description_fr: "Omelette préparée avec poêlée de champignons sauvages et herbes fraîches.",
    price: 25,
    calories: 410,
    image_url: "https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "sandwiches",
    item_id: "roasted_chicken_sandwich",
    name_en: "Roasted Chicken Sandwich",
    name_ar: "ساندوتش دجاج مشوي",
    name_fr: "Sandwich Poulet Rôti Artisanal",
    description_en: "Tender herb-roasted chicken breast with crispy lettuce, tomatoes, and chef sauce on toasted bread.",
    description_ar: "صدر دجاج متبل ومشوي مع الخس الطازج، الطماطم وصلصة الشيف الخاصة.",
    description_fr: "Blanc de poulet mariné et rôti, salade croquante, tomates et sauce maison.",
    price: 29,
    calories: 510,
    image_url: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "sandwiches",
    item_id: "mozzarella_lettuce_tomato",
    name_en: "Mozzarella, Lettuce & Tomato Sandwich",
    name_ar: "جبنة الموزاريلا مع الخس والطماطم",
    name_fr: "Sandwich Mozzarella, Salade & Tomate",
    description_en: "Fresh Italian mozzarella, crisp lettuce, sun-ripened tomatoes, and balsamic pesto drizzle.",
    description_ar: "جبنة موزاريلا إيطالية طازجة مع الخس المقرمش والطماطم وصلصة الريحان.",
    description_fr: "Mozzarella fraîche fondante, salade craquante, tomates mûres et filet de pesto.",
    price: 29,
    calories: 440,
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "sandwiches",
    item_id: "cheesy_tuna_melt",
    name_en: "Cheesy Tuna Melt",
    name_ar: "الجبن الذائب مع التونة",
    name_fr: "Tuna Melt Fromage Fondu",
    description_en: "Warm toasted sandwich with seasoned tuna salad under a blanket of bubbly melted cheese.",
    description_ar: "توست ساخن ومقرمش مع سلطة التونة المتبلة المغطاة بالجبن الذائب والشهي.",
    description_fr: "Sandwich chaud grillé garni de salade de thon assaisonnée et fromage gratiné.",
    price: 29,
    calories: 520,
    image_url: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "pastas",
    item_id: "pomodoro_pasta",
    name_en: "Classic Pomodoro Pasta",
    name_ar: "بومودورو باستا كلاسيكية",
    name_fr: "Pâtes Pomodoro Italiennes",
    description_en: "Al dente spaghetti tossed in slow-simmered rich tomato sauce, basil, garlic, and fresh parmesan.",
    description_ar: "سباغيتي إيطالية مطبوخة مع صلصة الطماطم الغنية بالريحان والثوم وجبن البارميزان.",
    description_fr: "Pâtes al dente préparées dans une sauce tomate mijotée, basilic frais et parmesan.",
    price: 29,
    calories: 480,
    image_url: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "pastas",
    item_id: "grilled_chicken_pesto",
    name_en: "Grilled Chicken Pesto Pasta",
    name_ar: "دجاج مشوي مع صلصة البيستو",
    name_fr: "Pâtes au Pesto & Poulet Grillé",
    description_en: "Tender grilled chicken strips over pasta coated with aromatic basil pesto cream and roasted pine nuts.",
    description_ar: "قطع الدجاج المشوي الشهي مع الباستا المغطاة بكريمة البيستو العطرة وجبن البارميزان.",
    description_fr: "Aiguillettes de poulet grillé sur lit de pâtes crémeuses au pesto de basilic.",
    price: 29,
    calories: 560,
    image_url: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "pastas",
    item_id: "carbonara_pasta",
    name_en: "Creamy Carbonara Pasta",
    name_ar: "كاربونارا إيطالية كريمية",
    name_fr: "Pâtes Carbonara Onctueuses",
    description_en: "Rich and creamy pasta with crispy beef bacon, cracked black pepper, and parmesan cheese.",
    description_ar: "باستا كريمية غنية مع لحم البقر المقرمش والفلفل الأسود المجروش وجبن البارميزان.",
    description_fr: "Pâtes à la crème parfumée, bacon de bœuf croustillant, poivre noir et parmesan.",
    price: 29,
    calories: 620,
    image_url: "https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 2. COMBOS & VALUE MEALS =================
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "value_meal_drink_food",
    name_en: "Value Meal (1 Small Drink + 1 Food)",
    name_ar: "وجبة اقتصادية (مشروب صغير + صنف طعام)",
    name_fr: "Formule Éco (1 Boisson + 1 Viennoiserie/Pâtisserie)",
    description_en: "Choice of small hot/iced coffee or mojito paired with your choice of croissant, cinnamon roll or cookie.",
    description_ar: "اختر مشروبك المفضل الصغير (قهوة ساخنة/باردة أو موهيتو) مع صنف طعام (كرواسون، رول قرفة أو كوكيز).",
    description_fr: "Au choix : boisson chaude/glacée ou mojito + croissant, roulé cannelle ou cookie.",
    price: 20,
    calories: 450,
    image_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "value_meal_cake_coffee",
    name_en: "Cake & Brewed Coffee Combo",
    name_ar: "وجبة الكيك + قهوة أمريكانو كبيرة",
    name_fr: "Combo Part de Gâteau & Grand Café",
    description_en: "Buy 1 cake slice of your choice and enjoy a Large Americano or Brewed Coffee.",
    description_ar: "اشتر قطعة كعكة من اختيارك واستمتع بكوب كبير من أمريكانو أو قهوة سادة.",
    description_fr: "Une part de gâteau au choix accompagnée d'un grand Americano ou café filtre.",
    price: 25,
    calories: 510,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_croissant_combo",
    name_en: "Red Bull Combo (Croissant + Energy Drink)",
    name_ar: "كومبو ريد بُل (كرواسون + مشروب طاقة)",
    name_fr: "Combo Red Bull (Croissant + Boisson Énergisante)",
    description_en: "Any fresh croissant paired with a can of Red Bull Energy Drink.",
    description_ar: "أي كرواسون طازج من اختيارك مع مشروب طاقة ريد بُل المنعش.",
    description_fr: "Croissant au choix et canette de Red Bull Energy Drink.",
    price: 25,
    calories: 380,
    image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_salad_combo",
    name_en: "Red Bull Combo (Salad + Energy Drink)",
    name_ar: "كومبو ريد بُل (سلطة + مشروب طاقة)",
    name_fr: "Combo Red Bull (Salade + Boisson Énergisante)",
    description_en: "Any fresh healthy salad paired with a can of Red Bull Energy Drink.",
    description_ar: "أي سلطة صحية طازجة من اختيارك مع مشروب طاقة ريد بُل.",
    description_fr: "Salade fraîche au choix et canette de Red Bull Energy Drink.",
    price: 35,
    calories: 320,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_mojito_croissant",
    name_en: "Red Bull Mojito & Croissant Combo",
    name_ar: "كومبو موهيتو ريد بُل + كرواسون",
    name_fr: "Combo Mojito Red Bull & Croissant",
    description_en: "Refreshing crafted Red Bull Mojito drink served with any fresh croissant.",
    description_ar: "موهيتو ريد بُل المميز والمنعش مع أي كرواسون طازج.",
    description_fr: "Mojito préparé au Red Bull et croissant frais au choix.",
    price: 29,
    calories: 390,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_mojito_salad",
    name_en: "Red Bull Mojito & Salad Combo",
    name_ar: "كومبو موهيتو ريد بُل + سلطة",
    name_fr: "Combo Mojito Red Bull & Salade",
    description_en: "Refreshing crafted Red Bull Mojito drink served with any fresh gourmet salad.",
    description_ar: "موهيتو ريد بُل الفاخر والمنعش مع أي سلطة طازجة من اختيارك.",
    description_fr: "Mojito pétillant au Red Bull et salade gourmande au choix.",
    price: 39,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 3. CAKES & CHEESECAKES =================
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "blueberry_cheesecake",
    name_en: "Blueberry Cheesecake",
    name_ar: "تشيزكيك التوت الأزرق",
    name_fr: "Cheesecake aux Myrtilles",
    description_en: "Creamy baked cheesecake with a rich blueberry compote glaze.",
    description_ar: "تشيز كيك كريمي مخبوز مغطى بطبقة من التوت الأزرق الطبيعي.",
    description_fr: "Cheesecake onctueux surmonté d'un coulis gourmand de myrtilles.",
    price: 20,
    calories: 420,
    image_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "banana_cake_slice",
    name_en: "Banana Cake Slice",
    name_ar: "شريحة كعكة الموز",
    name_fr: "Part de Banana Bread Moelleux",
    description_en: "Moist freshly baked banana loaf slice with natural sweetness.",
    description_ar: "شريحة طازجة من كعكة الموز الهشة والمخبوزة بحب.",
    description_fr: "Moelleux au goût authentique de banane fraîche et cannelle.",
    price: 14,
    calories: 290,
    image_url: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "victoria_cake",
    name_en: "Victoria Sponge Cake",
    name_ar: "كيك فيكتوريا الملكي",
    name_fr: "Gâteau Victoria Éponge",
    description_en: "Classic British layered sponge cake filled with sweet jam and vanilla cream.",
    description_ar: "كعكة فيكتوريا الإسفنجية الكلاسيكية المحشوة بالمربى وكريمة الفانيليا الفاخرة.",
    description_fr: "Gâteau génoise traditionnel fourré à la crème vanille et confiture de fraise.",
    price: 22,
    calories: 380,
    image_url: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "classic_ny_cheesecake",
    name_en: "Classic New York Cheesecake",
    name_ar: "تشيز كيك نيويورك الكلاسيكي",
    name_fr: "Véritable Cheesecake New-Yorkais",
    description_en: "Dense, velvety smooth New York style cheesecake on a buttery graham crust.",
    description_ar: "تشيز كيك نيويورك الغني والمخبوز بنعومة فائقة على قاعدة بسكويت مقرمشة.",
    description_fr: "Cheesecake crémeux et fondant sur croûte de biscuit croustillant.",
    price: 23,
    calories: 450,
    image_url: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "tiramisu_cake",
    name_en: "Tiramisu Cake",
    name_ar: "كيكة التيراميسو الإيطالية",
    name_fr: "Gâteau Tiramisu au Mascarpone",
    description_en: "Espresso-soaked sponge layered with whipped mascarpone cream and dusted with cocoa.",
    description_ar: "طبقات من البسكويت المشبع بقهوة الإسبريسو مع كريمة الماسكاربوني وبودرة الكاكاو الفاخرة.",
    description_fr: "Génoise imbibée d'espresso Bo's, crème mascarpone aérée et cacao amer.",
    price: 21,
    calories: 390,
    image_url: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "salted_caramel_cheesecake",
    name_en: "Salted Caramel Cheesecake",
    name_ar: "تشيز كيك الكراميل المملح",
    name_fr: "Cheesecake Caramel Beurre Salé",
    description_en: "Rich cheesecake swirled with homemade salted caramel ribbon.",
    description_ar: "تشيز كيك كريمي ممزوج بصلصة الكراميل المملح الغنية والمتوازنة.",
    description_fr: "Cheesecake savoureux marbré d'un caramel fondant au sel marin.",
    price: 21,
    calories: 460,
    image_url: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "mango_cheesecake",
    name_en: "Mango Cheesecake",
    name_ar: "مانجو تشيزكيك استوائي",
    name_fr: "Cheesecake Mangue Tropicale",
    description_en: "Tropical sweet mango purée poured over a velvety chilled cheesecake.",
    description_ar: "تشيز كيك بارد ومنعش مغطى ببيوريه المانجو الاستوائي الطازج.",
    description_fr: "Cheesecake frais recouvert d'un coulis pur de mangue tropicale.",
    price: 24,
    calories: 410,
    image_url: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "dates_walnut_slice_cake",
    name_en: "Dates & Walnut Slice Cake",
    name_ar: "كعكة التمر والجوز",
    name_fr: "Moelleux Dattes & Noix",
    description_en: "Traditional Middle Eastern spiced date cake studded with crunchy toasted walnuts.",
    description_ar: "كعكة التمر الطبيعي الفاخر مع حبات الجوز المحمص المقرمش.",
    description_fr: "Gâteau riche aux dattes de qualité supérieure et éclats de noix croquantes.",
    price: 14,
    calories: 330,
    image_url: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "chocolate_fudge_cake",
    name_en: "Chocolate Fudge Cake",
    name_ar: "كيكة الشوكولاتة المركزة (فادج)",
    name_fr: "Gâteau Tout Chocolat Fudge",
    description_en: "Decadent multi-layered dark chocolate fudge cake with silky chocolate ganache.",
    description_ar: "كعكة الشوكولاتة الداكنة الفاخرة بطبقات الفادج الغنية وكريمة الشوكولاتة الذائبة.",
    description_fr: "Gâteau ultra-fondant au chocolat noir intense et ganache onctueuse.",
    price: 22,
    calories: 490,
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "walnut_brownie",
    name_en: "Walnut Brownie",
    name_ar: "براوني بالجوز الغني",
    name_fr: "Brownie Chocolat & Noix",
    description_en: "Dense, fudgy chocolate square baked with premium walnuts.",
    description_ar: "قطعة براوني شوكولاتة كثيفة وغنية محشوة بقطع الجوز المقرمش.",
    description_fr: "Carré de brownie au cœur coulant parsemé de noix croustillantes.",
    price: 16,
    calories: 370,
    image_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 4. COOKIES, CROISSANTS & VIENNOISERIE =================
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chocolate_chunk_cookie",
    name_en: "Chocolate Chunk Cookie",
    name_ar: "كوكيز بقطع الشوكولاتة",
    name_fr: "Cookie aux Pépites de Chocolat",
    description_en: "Warm golden cookie packed with gooey Belgian chocolate chunks.",
    description_ar: "كوكيز ذهبي طري محشو بقطع الشوكولاتة الذائبة اللذيذة.",
    description_fr: "Cookie croustillant à l'extérieur et fondant au cœur avec gros morceaux de chocolat.",
    price: 10,
    calories: 260,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "oatmeal_raisin_cookie",
    name_en: "Oatmeal Raisin Cookie",
    name_ar: "كوكيز الشوفان والزبيب",
    name_fr: "Cookie Avoine & Raisins Secs",
    description_en: "Wholesome rolled oats and sweet plump raisins with a hint of cinnamon.",
    description_ar: "كوكيز الشوفان الصحي المقرمش مع الزبيب الحلو ولمسة قرفة دافئة.",
    description_fr: "Cookie aux flocons d'avoine et raisins blonds moelleux parfumés à la cannelle.",
    price: 10,
    calories: 230,
    image_url: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "butter_croissant",
    name_en: "Butter Croissant",
    name_ar: "كرواسون فرنسي بالزبدة",
    name_fr: "Croissant Pur Beurre AOP",
    description_en: "Golden, flaky, French-style croissant made with pure butter.",
    description_ar: "كرواسون فرنسي ذهبي وهش محضر بالزبدة النقية.",
    description_fr: "Feuilletage doré et aéré au bon goût de beurre frais.",
    price: 10,
    calories: 270,
    image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "almond_croissant",
    name_en: "Almond Croissant",
    name_ar: "كرواسون اللوز المقرمش",
    name_fr: "Croissant aux Amandes Effilées",
    description_en: "Filled with sweet almond frangipane and topped with toasted almond flakes.",
    description_ar: "محشو بكريمة اللوز الغنية ومغطى بشرائح اللوز المحمصة وسكر ناعم.",
    description_fr: "Garni d'une généreuse crème d'amande et saupoudré d'amandes grillées.",
    price: 10,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chocolate_croissant",
    name_en: "Chocolate Croissant",
    name_ar: "كرواسون بالشوكولاتة",
    name_fr: "Pain au Chocolat Feuilleté",
    description_en: "Flaky pastry wrapped around twin batons of dark chocolate.",
    description_ar: "عجينة مورقة هشة محشوة بأعواد الشوكولاتة الداكنة الذائبة.",
    description_fr: "Viennoiserie croustillante avec deux barres de chocolat noir fondant.",
    price: 10,
    calories: 310,
    image_url: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "zaatar_croissant",
    name_en: "Zaatar Croissant",
    name_ar: "كرواسون بالزعتر البري",
    name_fr: "Croissant au Zaatar & Huile d'Olive",
    description_en: "Savory pastry dusted with aromatic Mediterranean wild zaatar herb blend.",
    description_ar: "كرواسون مالح هش متبل بخلطة الزعتر البري وزيت الزيتون البكر.",
    description_fr: "Croissant salé parfumé au thym sauvage libanais et huile d'olive.",
    price: 11,
    calories: 280,
    image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "three_cheese_croissant",
    name_en: "Three Cheese Croissant",
    name_ar: "كرواسون ثلاثة أجبان",
    name_fr: "Croissant aux Trois Fromages",
    description_en: "Stuffed with melted mozzarella, cheddar, and creamy cheese.",
    description_ar: "كرواسون هش محشو بمزيج غني من ثلاثة أجبان ذائبة.",
    description_fr: "Croissant croustillant fourré d'un mélange fondant de trois fromages.",
    price: 12,
    calories: 350,
    image_url: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chocolate_twist",
    name_en: "Chocolate Twist",
    name_ar: "تويست الشوكولاتة المقرمش",
    name_fr: "Torsade au Chocolat & Crème Pâtissière",
    description_en: "Twisted pastry ribbons with rich pastry cream and chocolate chips.",
    description_ar: "عجينة مورقة ملتوية ومحشوة بكريمة الحلواني ورقائق الشوكولاتة.",
    description_fr: "Viennoiserie torsadée garnie de crème pâtissière et pépites de chocolat.",
    price: 12,
    calories: 320,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "cinnamon_roll",
    name_en: "Cinnamon Roll",
    name_ar: "لفائف القرفة (سينامون رول)",
    name_fr: "Roulé Gourmand à la Cannelle",
    description_en: "Soft swirled sweet dough packed with brown sugar cinnamon and vanilla icing glaze.",
    description_ar: "لفائف طرية ودافئة مع حشوة القرفة والسكر البني وصوص الفانيليا اللذيذ.",
    description_fr: "Brioche roulée moelleuse aux épices de cannelle et glaçage sucré.",
    price: 11,
    calories: 360,
    image_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 5. MUFFINS =================
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "blueberry_streusel_muffin",
    name_en: "Blueberry Streusel Muffin",
    name_ar: "مافن التوت والستروسل",
    name_fr: "Muffin Myrtilles & Crumble Streusel",
    description_en: "Jumbo muffin bursting with juicy blueberries and a crunchy sweet crumble top.",
    description_ar: "مافن طري غني بحبات التوت الأزرق الطبيعي ومغطى بفتات الستروسل المقرمش.",
    description_fr: "Gros muffin généreux en myrtilles avec dessus croustillant façon crumble.",
    price: 15,
    calories: 380,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "carrot_oatmeal_raisins_muffin",
    name_en: "Carrot Oatmeal Raisins Muffin",
    name_ar: "مافن الجزر والشوفان والزبيب",
    name_fr: "Muffin Carotte, Avoine & Raisins",
    description_en: "Spiced spiced carrot cake muffin with oats and sweet raisins.",
    description_ar: "مافن الجزر المتبل مع الشوفان والزبيب وحبات التوابل العطرية.",
    description_fr: "Muffin façon carrot cake riche en flocons d'avoine et raisins blonds.",
    price: 11,
    calories: 310,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "choco_banana_muffin",
    name_en: "Choco Banana Muffin",
    name_ar: "مافن شوكولا الموز",
    name_fr: "Muffin Banane & Chocolat Fondant",
    description_en: "Moist banana muffin loaded with decadent melted chocolate drops.",
    description_ar: "مافن الموز الطري الممزوج بقطع الشوكولاتة الداكنة الذائبة.",
    description_fr: "Muffin très moelleux à la purée de banane et pépites de chocolat.",
    price: 11,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "double_choco_chip_muffin",
    name_en: "Double Choco Chip Muffin",
    name_ar: "مافن رقائق الشيكولا الوفيرة",
    name_fr: "Muffin Double Chocolat Noir",
    description_en: "All-chocolate muffin base generously packed with milk and dark chocolate chips.",
    description_ar: "مافن كاكاو مكثف محشو برقائق الشوكولاتة بالحليب والشوكولاتة الداكنة.",
    description_fr: "Muffin intensément chocolaté avec double dose de pépites fondantes.",
    price: 11,
    calories: 390,
    image_url: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 6. SALADS =================
  {
    instance_name: "bos_cafe_aspire",
    category: "salads",
    item_id: "chicken_fiesta_salad",
    name_en: "Chicken Fiesta Salad",
    name_ar: "سلطة الدجاج الاحتفالية",
    name_fr: "Salade Fiesta au Poulet Grillé",
    description_en: "Grilled marinated chicken with sweet corn, black beans, bell peppers, fresh greens, and cilantro vinaigrette.",
    description_ar: "دجاج مشوي متبل مع الذرة الحلوة، الفاصولياء، الفلفل الملون، الخضار وصلصة الكزبرة المنعشة.",
    description_fr: "Salade colorée au poulet grillé, maïs croquant, poivrons et vinaigrette aux herbes.",
    price: 19,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "salads",
    item_id: "farfalle_pasta_salad",
    name_en: "Farfalle Pasta Salad",
    name_ar: "سلطة مكرونة الفارفالي",
    name_fr: "Salade de Pâtes Farfalle Fraîcheur",
    description_en: "Farfalle bow-tie pasta with cherry tomatoes, olives, cucumbers, feta cheese, and Italian herb dressing.",
    description_ar: "باستا فارفالي الإيطالية مع طماطم كرزية، زيتون، خيار، جبن فيتا وصلصة الأعشاب الإيطالية.",
    description_fr: "Pâtes papillon avec tomates cerises, olives, concombres, feta et assaisonnement italien.",
    price: 19,
    calories: 370,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "salads",
    item_id: "mixed_vegetable_halloumi_salad",
    name_en: "Mixed Vegetable & Halloumi Salad",
    name_ar: "سلطة الخضروات المشكلة مع الحلوم",
    name_fr: "Salade Maraîchère & Halloumi Grillé",
    description_en: "Crispy grilled halloumi cheese cubes over fresh mixed greens, cucumbers, and pomegranate vinaigrette.",
    description_ar: "مكعبات جبن الحلوم المشوي مع الخضار المشكلة الطازجة والخيار وصوص دبس الرمان.",
    description_fr: "Fromage halloumi doré à la plancha sur mélange de jeunes pousses et vinaigrette grenade.",
    price: 19,
    calories: 320,
    image_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "salads",
    item_id: "couscous_salad",
    name_en: "Mediterranean Couscous Salad",
    name_ar: "سلطة الكسكس المتوسطية",
    name_fr: "Salade de Couscous Méditerranéenne",
    description_en: "Light seasoned couscous mixed with diced roasted vegetables, herbs, and lemon olive oil dressing.",
    description_ar: "حبات الكسكس الخفيفة مع الخضار المشوية المتبلة وزيت الزيتون وعصير الليمون المنعش.",
    description_fr: "Semoule de couscous parfumée aux petits légumes rôtis, menthe fraîche et citron.",
    price: 19,
    calories: 290,
    image_url: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 7. ESPRESSO & CLASSIC COFFEES =================
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "espresso_single",
    name_en: "Espresso (Single / Double)",
    name_ar: "إسبريسو (سولو / دوبيو)",
    name_fr: "Espresso Bo's (Simple / Double)",
    description_en: "Intense, rich shot of single-origin Philippine Arabica coffee with golden crema.",
    description_ar: "جرعة إسبريسو مركزة وغنية من حبوب البن الفلبيني الفاخر بكريمة ذهبية.",
    description_fr: "Extraction pure de grains arabica premium avec une crema veloutée.",
    price: 10,
    calories: 5,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "espresso_macchiato",
    name_en: "Espresso Macchiato",
    name_ar: "إسبريسو ماكياتو",
    name_fr: "Espresso Macchiato Mousse de Lait",
    description_en: "Bold espresso topped with a velvety dollop of steamed milk foam.",
    description_ar: "إسبريسو قوي تعلوه رشفة من رغوة الحليب المبخر الناعمة.",
    description_fr: "Espresso serré surmonté d'une touche de mousse de lait crémeuse.",
    price: 10,
    calories: 25,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "americano",
    name_en: "Americano (Hot / Iced)",
    name_ar: "أمريكانو (ساخن / بارد)",
    name_fr: "Café Americano (Chaud ou Glacé)",
    description_en: "Espresso lengthened with hot or cold filtered water for a clean, aromatic coffee experience.",
    description_ar: "إسبريسو ممدد بالماء النقي الساخن أو المثلج لنكهة بن متوازنة ومميزة.",
    description_fr: "Allongé d'eau filtrée pour révéler les notes délicates du terroir philippin.",
    price: 12,
    calories: 10,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "cafe_latte",
    name_en: "Café Latte (Hot / Iced)",
    name_ar: "كافيه لاتيه (ساخن / بارد)",
    name_fr: "Café Latte Onctueux (Chaud / Glacé)",
    description_en: "Rich espresso combined with steamed velvety milk and a light foam layer.",
    description_ar: "مزيج الإسبريسو الغني مع الحليب المبخر ورغوة حليبية ناعمة ولذيذة.",
    description_fr: "Équilibre parfait entre espresso aromatique et lait soyeux micro-moussé.",
    price: 15,
    calories: 180,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "cappuccino",
    name_en: "Cappuccino",
    name_ar: "كابتشينو كلاسيكي",
    name_fr: "Cappuccino Traditionnel",
    description_en: "Equal parts rich espresso, steamed milk, and a cloud of fluffy milk froth.",
    description_ar: "إسبريسو غني مع الحليب المبخر ورغوة حليب كثيفة وغنية بالرائحة الذكية.",
    description_fr: "Espresso profond couronné d'un dôme de mousse de lait dense et aérien.",
    price: 15,
    calories: 150,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "cafe_mocha",
    name_en: "Café Mocha (Hot / Iced)",
    name_ar: "كافيه موكا (ساخن / بارد)",
    name_fr: "Café Mocha Chocolaté (Chaud / Glacé)",
    description_en: "Rich espresso blended with dark chocolate sauce, steamed milk, and whipped cream.",
    description_ar: "إسبريسو مركز ممزوج بصلصة الشوكولاتة الداكنة والحليب المبخر مع الكريمة المخفوقة.",
    description_fr: "Alliance gourmande d'espresso et sauce chocolat noir, nappée de chantilly.",
    price: 17,
    calories: 290,
    image_url: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "caramel_latte",
    name_en: "Caramel Latte",
    name_ar: "كراميل لاتيه",
    name_fr: "Caramel Latte Gourmand",
    description_en: "Smooth café latte infused with golden butter caramel syrup.",
    description_ar: "لاتيه ناعم بنكهة الكراميل الذهبي الزبدية الغنية والمحبوبة.",
    description_fr: "Latte velouté rehaussé de sirop de caramel doré onctueux.",
    price: 17,
    calories: 240,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "white_chocolate_mocha",
    name_en: "White Chocolate Mocha",
    name_ar: "موكا الشوكولاتة البيضاء",
    name_fr: "Mocha au Chocolat Blanc",
    description_en: "Espresso infused with creamy sweet white chocolate sauce and steamed milk.",
    description_ar: "إسبريسو ممزوج بالشوكولاتة البيضاء الحريرية والحليب المبخر.",
    description_fr: "Espresso doux marié à un chocolat blanc onctueux et lait chaud.",
    price: 17,
    calories: 310,
    image_url: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "signature_chocolate",
    name_en: "Signature Bo's Hot Chocolate",
    name_ar: "شوكولاتة ضيافة بوس كوفي الخاصة",
    name_fr: "Chocolat Chaud Signature Bo's",
    description_en: "Decadent melted chocolate with steamed fresh milk and whipped cream.",
    description_ar: "شوكولاتة دافئة غنية ولذيذة ومحلاة برغوة الحليب والكريمة المخفوقة.",
    description_fr: "Chocolat chaud épais et réconfortant selon la recette maison Bo's.",
    price: 17,
    calories: 330,
    image_url: "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "spanish_latte",
    name_en: "Spanish Latte (Hot / Iced)",
    name_ar: "لاتيه إسباني فاخر (ساخن / بارد)",
    name_fr: "Spanish Latte Signature (Chaud / Glacé)",
    description_en: "Signature sweetened condensed milk base topped with bold espresso and creamy cold milk.",
    description_ar: "المشروب الأكثر طلباً: حليب مكثف محلى مع إسبريسو غني وحليب بارد ومثلج.",
    description_fr: "Le grand favori du Moyen-Orient : lait concentré sucré, double espresso et lait frais.",
    price: 21,
    calories: 280,
    image_url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "rose_latte",
    name_en: "Rose Latte",
    name_ar: "روز لاتيه العطري",
    name_fr: "Latte aux Pétales de Rose",
    description_en: "Fragrant floral rose infusion with espresso, silky milk, and dried rose petals.",
    description_ar: "لاتيه فاخر بنكهة ماء الورد الطبيعي وخلاصة بتلات الورد العطرية.",
    description_fr: "Latte délicat infusé à l'essence de rose et décoré de pétales séchés.",
    price: 20,
    calories: 230,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "saffron_latte",
    name_en: "Saffron Latte",
    name_ar: "لاتيه الزعفران الملكي",
    name_fr: "Latte Impérial au Safran",
    description_en: "Golden royal latte infused with authentic Persian saffron threads and aromatic spices.",
    description_ar: "لاتيه ملكي باللون الذهبي بنكهة خيوط الزعفران الأصلي والبهارات العطرية.",
    description_fr: "Breuvage d'exception teinté d'or et parfumé aux précieux pistils de safran.",
    price: 20,
    calories: 250,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "salted_caramel_latte",
    name_en: "Salted Caramel Latte",
    name_ar: "مملح كراميل لاتيه",
    name_fr: "Latte Caramel Beurre Salé",
    description_en: "Espresso and steamed milk swirled with sweet and salty artisan caramel syrup.",
    description_ar: "لاتيه رائع بنكهة الكراميل المملح المتوازنة بين الحلاوة والملوحة الخفيفة.",
    description_fr: "L'accord parfait entre sel marin, caramel gourmand et café corsé.",
    price: 20,
    calories: 260,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "french_vanilla_latte",
    name_en: "French Vanilla Latte",
    name_ar: "لاتيه بنكهة الفانيليا الفرنسية",
    name_fr: "Latte Vanille Bourbon Française",
    description_en: "Smooth café latte sweetened with fragrant pure French vanilla bean syrup.",
    description_ar: "لاتيه ناعم وحريري بنكهة خلاصة الفانيليا الفرنسية الكلاسيكية.",
    description_fr: "Douceur de vanille française enveloppée dans un lait mousseux bien chaud.",
    price: 20,
    calories: 240,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "french_press_brewed",
    name_en: "Bo's French Press Brewed Coffee",
    name_ar: "قهوة فرنش بريس فلتر",
    name_fr: "Café Filtre French Press Bo's",
    description_en: "Freshly ground single-origin Philippine beans steeped and pressed to order.",
    description_ar: "حبوب بن فلبينية طازجة تُطحن وتُحضر عبر مكبس الفرنش بريس عند الطلب.",
    description_fr: "Café d'origine unique extrait par infusion lente en cafetière à piston.",
    price: 17,
    calories: 5,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "tea_bag_selection",
    name_en: "Fine Gourmet Tea Bag Selection",
    name_ar: "شاي ساخن فاخر مشكل",
    name_fr: "Sélection de Thés & Infusions Prestige",
    description_en: "Selection of English Breakfast, Earl Grey, Green Tea, or Peppermint.",
    description_ar: "تشكيلة شاي ساخنة فاخرة: إنجليزي، إيرل جراي، شاي أخضر أو نعناع.",
    description_fr: "Sachets de thés nobles : Breakfast, Earl Grey, Vert Sencha ou Menthe poivrée.",
    price: 11,
    calories: 0,
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 8. MOJITOS & REFRESHERS =================
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "blue_lagoon_mojito",
    name_en: "Blue Lagoon Mojito",
    name_ar: "موهيتو بلو لاجون المنعش",
    name_fr: "Mojito Blue Lagoon Givré",
    description_en: "Vibrant blue curaçao flavor with fresh mint, lime slices, sparkling soda, and crushed ice.",
    description_ar: "موهيتو أزرق منعش بنكهة الكوراساو مع النعناع والليمون الطازج والصودا الفوارة.",
    description_fr: "Cocktail sans alcool turquoise aux notes d'agrumes, menthe fraîche et citron vert.",
    price: 19,
    calories: 140,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "passion_fruit_mojito",
    name_en: "Passion Fruit Mojito",
    name_ar: "موهيتو باشون فروت الاستوائي",
    name_fr: "Mojito Fruit de la Passion",
    description_en: "Tangy tropical passion fruit seeds and syrup with fresh crushed mint and chilled soda.",
    description_ar: "نكهة الباشون فروت الاستوائية مع النعناع المنعش والليمون والصودا المثلجة.",
    description_fr: "Saveur exotique de fruit de la passion avec menthe pilée et eau pétillante.",
    price: 19,
    calories: 150,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "red_berries_mojito",
    name_en: "Red Berries Mojito",
    name_ar: "موهيتو التوت الأحمر",
    name_fr: "Mojito Fruits Rouges Pétillant",
    description_en: "Muddled fresh raspberries, blackberries, and strawberries with mint and lime soda.",
    description_ar: "مزيج التوت الأحمر المنعش مع أوراق النعناع وشرائح الليمون والصودا الباردة.",
    description_fr: "Mélange de framboises, mûres et fraises avec menthe fraîche et bulles fines.",
    price: 19,
    calories: 145,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "strawberry_mojito",
    name_en: "Strawberry Mojito",
    name_ar: "موهيتو فراولة طبيعية",
    name_fr: "Mojito Fraises Fraîches",
    description_en: "Sweet strawberry purée shaken with lime juice, mint leaves, and ice-cold soda.",
    description_ar: "عصير الفراولة الطبيعية مع الليمون الحامض والنعناع المنعش ومكعبات الثلج.",
    description_fr: "Douceur de fraises écrasées avec jus de lime acidulé et menthe fraîche.",
    price: 19,
    calories: 140,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "classic_mojito",
    name_en: "Classic Lime & Mint Mojito",
    name_ar: "موهيتو كلاسيك بالليمون والنعناع",
    name_fr: "Mojito Citron Vert & Menthe Fraîche",
    description_en: "The original thirst quencher: muddled fresh mint, lime wedges, cane sugar, and sparkling soda.",
    description_ar: "الموهيتو الكلاسيكي الأصلي بالنعناع المهروس وقطع الليمون الطازجة ومكعبات الثلج.",
    description_fr: "La recette cubaine rafraîchissante : menthe fraîche pilée, quartier de lime et soda glacé.",
    price: 19,
    calories: 120,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "mint_mojito",
    name_en: "Fresh Mint Mojito",
    name_ar: "موهيتو النعناع المنعش",
    name_fr: "Mojito Pure Menthe Fraîche",
    description_en: "Double shot of fresh green spearmint muddled with lime and crushed crystal ice.",
    description_ar: "جرعة مزدوجة من النعناع الأخضر المنعش مع الليمون الحامض ومسحوق الثلج.",
    description_fr: "Explosion de fraîcheur végétale avec double dose de feuilles de menthe.",
    price: 19,
    calories: 120,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  }
];

async function insertItems() {
  console.log(`Starting insertion of ${items.length} items for Bo's Coffee - Aspire Park...`);
  
  const batchSize = 25;
  for (let i = 0; i < items.length; i += batchSize) {
    const batch = items.slice(i, i + batchSize);
    const postData = JSON.stringify(batch);

    const options = {
      hostname: NOCODB_HOST,
      port: NOCODB_PORT,
      path: `/api/v2/tables/${TABLE_ID}/records`,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'xc-token': NOCODB_TOKEN,
        'Content-Length': Buffer.byteLength(postData)
      }
    };

    await new Promise((resolve) => {
      const req = http.request(options, (res) => {
        let body = '';
        res.on('data', chunk => body += chunk);
        res.on('end', () => {
          console.log(`Batch ${Math.floor(i / batchSize) + 1} (${batch.length} items) - HTTP Status: ${res.statusCode}`);
          resolve(body);
        });
      });

      req.on('error', (e) => {
        console.error(`Error in batch ${i}:`, e);
        resolve(null);
      });

      req.write(postData);
      req.end();
    });
  }

  console.log("SUCCESS: All items successfully inserted into NocoDB!");
}

insertItems();
