const http = require('http');

const NOCODB_HOST = "srv821341.hstgr.cloud";
const NOCODB_PORT = 8086;
const NOCODB_TOKEN = "nc_pat_6hZw4JgAjaFFfNbC7ui1IP4nuCi1mWWWq816JqFs";
const TABLE_ID = "mo1b63dokvbmjyg"; // menu_Items

const newItems = [
  // ================= 1. FROCCINO (8 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_espresso_crumble",
    name_en: "Espresso Crumble Froccino",
    name_ar: "اسبريسو كرامبل فروتشينو",
    name_fr: "Froccino Espresso Crumble",
    description_en: "Blended espresso with rich chocolate sauce, cookie crumble, and whipped cream.",
    description_ar: "فرابيه إسبريسو غني مع صوص الشوكولاتة وقطع الكوكيز المقرمشة مع الكريمة المخفوقة.",
    description_fr: "Froccino glacé à l'espresso, sauce chocolat, crumble de biscuits croustillants et chantilly.",
    price: 20,
    calories: 410,
    image_url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_caramelo",
    name_en: "Caramelo Froccino",
    name_ar: "كراميلو فروتشينو",
    name_fr: "Froccino Caramelo",
    description_en: "Signature blended coffee with golden caramel sauce, milk, and caramel drizzle.",
    description_ar: "مزيج القهوة المثلجة مع صوص الكراميل الذهبي اللذيذ والكريمة المخفوقة.",
    description_fr: "Café glacé onctueux au caramel doré avec filet de caramel et chantilly.",
    price: 20,
    calories: 390,
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_mocha",
    name_en: "Mocha Froccino",
    name_ar: "موكا فروتشينو",
    name_fr: "Froccino Mocha",
    description_en: "Blended espresso and rich Dutch cocoa topped with velvety whipped cream.",
    description_ar: "قهوة مثلجة مخلوطة مع الكاكاو الغني والكريمة المخفوقة وصلصة الشوكولاتة.",
    description_fr: "Café glacé au cacao hollandais riche surmonté d'une chantilly onctueuse.",
    price: 20,
    calories: 380,
    image_url: "https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_white_chocolate_mocha",
    name_en: "White Chocolate Mocha Froccino",
    name_ar: "موكا الشوكولاتة البيضاء فروتشينو",
    name_fr: "Froccino Mocha Chocolat Blanc",
    description_en: "Smooth white chocolate blended with espresso, ice, and whipped cream.",
    description_ar: "شوكولاتة بيضاء ناعمة مدمجة مع الإسبريسو والثلج مع الكريمة الفاخرة.",
    description_fr: "Chocolat blanc soyeux mixé avec espresso, glace pilée et crème fouettée.",
    price: 20,
    calories: 420,
    image_url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_coffee_jelly",
    name_en: "Coffee Jelly Froccino",
    name_ar: "جيلي القهوة فروتشينو",
    name_fr: "Froccino Gelée de Café",
    description_en: "Refreshing coffee frappe layered with chewy artisan coffee jelly cubes.",
    description_ar: "فرابيه القهوة المنعش مع مكعبات جيلي القهوة الشهية والمميزة.",
    description_fr: "Frappé au café rafraîchissant avec cubes fondants de gelée de café artisanal.",
    price: 20,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_cookies_cream",
    name_en: "Cookies & Cream Froccino",
    name_ar: "كوكيز وكريم فروتشينو",
    name_fr: "Froccino Cookies & Cream",
    description_en: "Crunchy chocolate cookies blended with milk and sweet cream, finished with cookie dust.",
    description_ar: "قطع بسكويت الشوكولاتة المقرمشة ممزوجة بالحليب والكريمة المخفوقة.",
    description_fr: "Biscuits chocolatés croquants mixés au lait et crème douce, saupoudrés de brisures.",
    price: 20,
    calories: 450,
    image_url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_chocolate_chip",
    name_en: "Chocolate Chip Froccino",
    name_ar: "قطع الشوكولاتة فروتشينو",
    name_fr: "Froccino Pépites de Chocolat",
    description_en: "Decadent blend of chocolate chips, rich mocha coffee, and whipped cream.",
    description_ar: "مزيج غني من رقائق الشوكولاتة وقهوة الموكا اللذيذة مع الكريمة.",
    description_fr: "Mélange gourmand de pépites de chocolat croquantes, café moka et chantilly.",
    price: 20,
    calories: 440,
    image_url: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "froccino",
    item_id: "froccino_lotus_biscoff",
    name_en: "Lotus Biscoff Froccino",
    name_ar: "بسكويت اللوتس فروتشينو",
    name_fr: "Froccino Spéculoos Lotus",
    description_en: "Creamy blended coffee infused with Lotus Biscoff spread and biscuit crumble.",
    description_ar: "فرابيه فاخر بكريمة اللوتس الشهيرة وبسكويت بيسكوف المقرمش.",
    description_fr: "Café glacé crémeux infusé à la pâte de Spéculoos Lotus et éclats de biscuit.",
    price: 20,
    calories: 460,
    image_url: "https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 2. FREEZE (NON-COFFEE BLENDS) (7 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_artisanal_chocolate",
    name_en: "Artisanal Chocolate Freeze",
    name_ar: "شوكولاتة ماهرة فريز",
    name_fr: "Freeze Chocolat Artisanal",
    description_en: "Premium iced chocolate frappe without coffee, topped with chocolate drizzle and cream.",
    description_ar: "فرابيه الشوكولاتة الفاخرة بدون قهوة، مزين بصلصة الشوكولاتة والكريمة.",
    description_fr: "Frappé au chocolat pur sans café, nappé de coulis chocolaté et chantilly.",
    price: 19,
    calories: 350,
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_strawberry",
    name_en: "Strawberry Freeze",
    name_ar: "فراولة فريز",
    name_fr: "Freeze Fraise Gourmande",
    description_en: "Luscious real strawberry blended frappe, fruity, sweet, and ultra-refreshing.",
    description_ar: "فرابيه الفراولة الطبيعية المنعشة والمخفوقة بالكريمة اللذيذة.",
    description_fr: "Frappé onctueux aux fraises gourmandes, fruité, doux et rafraîchissant.",
    price: 19,
    calories: 310,
    image_url: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_vanilla",
    name_en: "Vanilla Freeze",
    name_ar: "فانيليا فريز",
    name_fr: "Freeze Vanille Bourbon",
    description_en: "Smooth French vanilla ice-blended smoothie with a velvety rich texture.",
    description_ar: "سموذي مثلج غني بالفانيليا الفرنسية الناعمة والكريمة المخفوقة.",
    description_fr: "Smoothie glacé onctueux à la vanille française et crème veloutée.",
    price: 19,
    calories: 320,
    image_url: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_cookies_cream",
    name_en: "Cookies & Cream Freeze",
    name_ar: "كوكيز وكريم فريز",
    name_fr: "Freeze Cookies & Crème",
    description_en: "Decadent caffeine-free milkshake blended with Oreo-style cookies and cream.",
    description_ar: "ميلك شيك غني بقطع الكوكيز والشوكولاتة بدون كافيين مع الكريمة.",
    description_fr: "Milk-shake gourmand sans caféine aux morceaux de cookies et crème vanillée.",
    price: 19,
    calories: 420,
    image_url: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_mixed_berry",
    name_en: "Mixed Berry Freeze",
    name_ar: "توت مشكل فريز",
    name_fr: "Freeze Baies Sauvages",
    description_en: "Bursting with blackberries, blueberries, and raspberries blended with ice and cream.",
    description_ar: "مزيج منعش من التوت الأسود والأزرق والفراولة المخفوقة مع الثلج.",
    description_fr: "Explosion de fruits rouges (mûres, myrtilles, framboises) mixés glacés.",
    price: 19,
    calories: 290,
    image_url: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_mango",
    name_en: "Mango Freeze",
    name_ar: "مانجو فريز",
    name_fr: "Freeze Mangue Exotique",
    description_en: "Tropical sweet mango nectar blended with crushed ice for the ultimate sunny treat.",
    description_ar: "عصير المانجو الاستوائي المثلج المخفوق بنعومة فائقة.",
    description_fr: "Nectar de mangue tropicale mixé glacé pour une fraîcheur exotique intense.",
    price: 19,
    calories: 280,
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "freeze",
    item_id: "freeze_matcha_green_tea",
    name_en: "Matcha Green Tea Freeze",
    name_ar: "ماتشا الشاي الأخضر فريز",
    name_fr: "Freeze Thé Vert Matcha",
    description_en: "Pure Japanese Uji matcha blended with sweet milk and ice, crowned with cream.",
    description_ar: "شاي ماتشا الأخضر الياباني الأصيل مخفوق مع الحليب والثلج والكريمة.",
    description_fr: "Pur thé vert Matcha d'Uji mixé avec du lait doux, glace pilée et chantilly.",
    price: 22,
    calories: 330,
    image_url: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 3. LEMONADE ICED TEA (3 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "lemonade_tea_tropical",
    name_en: "Tropical Lemonade Iced Tea",
    name_ar: "شاي تروبيكال ليموناضة مثلج",
    name_fr: "Thé Glacé Citronnade Tropicale",
    description_en: "Fresh brewed black tea blended with tropical fruit citrus nectar and ice.",
    description_ar: "شاي أسود طازج ممزوج مع نكهات الفواكه الاستوائية والليمون الحامض المنعش.",
    description_fr: "Thé noir infusé glacé aux fruits tropicaux et citronnade rafraîchissante.",
    price: 17,
    calories: 120,
    image_url: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "lemonade_tea_peach",
    name_en: "Peach Lemonade Iced Tea",
    name_ar: "شاي مثلج بالخوخ والليمون",
    name_fr: "Thé Glacé Pêche & Citron",
    description_en: "Classic aromatic iced tea infused with sweet peach juice and tangy lemon slices.",
    description_ar: "شاي مثلج كلاسيكي مع عصير الخوخ اللذيذ وشرائح الليمون.",
    description_fr: "Thé glacé classique infusé à la pêche juteuse et rondelles de citron vert.",
    price: 17,
    calories: 110,
    image_url: "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "lemonade_tea_mint",
    name_en: "Mint Lemonade",
    name_ar: "شاي الليمون بالنعناع",
    name_fr: "Citronnade Fraîche à la Menthe",
    description_en: "Zesty freshly squeezed lemonade blended with fresh fragrant garden mint leaves.",
    description_ar: "عصير ليموناضة طازج مخفوق مع أوراق النعناع الخضراء المنعشة.",
    description_fr: "Citronnade pressée revigorante mixée avec des feuilles de menthe fraîche.",
    price: 17,
    calories: 95,
    image_url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 4. SIGNATURE BEVERAGES (7 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_black_cortado",
    name_en: "Black Cortado",
    name_ar: "بلاك كورتادو",
    name_fr: "Cortado Black",
    description_en: "Intense short double espresso with minimal water for deep roasted aromatic notes.",
    description_ar: "دبل إسبريسو مكثف وقوي بنكهات حبوب البن المحمصة الفاخرة.",
    description_fr: "Double espresso court et puissant révélant les arômes intenses du café torréfié.",
    price: 13,
    calories: 10,
    image_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_classic_cortado",
    name_en: "Classic Cortado",
    name_ar: "كورتادو كلاسيك",
    name_fr: "Cortado Classique",
    description_en: "Balanced Spanish-style coffee: equal parts bold espresso and velvety steamed milk.",
    description_ar: "قهوة كورتادو الكلاسيكية بنسبة متساوية بين الإسبريسو والحليب المبخر.",
    description_fr: "Équilibre parfait 1:1 entre un espresso intense et un lait soyeux texturé.",
    price: 13,
    calories: 75,
    image_url: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_mocha_cortado",
    name_en: "Mocha Cortado",
    name_ar: "موكا كورتادو",
    name_fr: "Cortado Moka",
    description_en: "Rich espresso cortado delicately infused with velvety Dutch chocolate.",
    description_ar: "قهوة الكورتادو مع لمسة من الشوكولاتة الهولندية الفاخرة.",
    description_fr: "Cortado intense adouci par une touche veloutée de chocolat hollandais.",
    price: 14,
    calories: 95,
    image_url: "https://images.unsplash.com/photo-1589396575653-c09c794ff6a6?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_caramel_cortado",
    name_en: "Caramel Cortado",
    name_ar: "كراميل كورتادو",
    name_fr: "Cortado Caramel",
    description_en: "Cortado sweetened with creamy golden caramel sauce and velvety microfoam.",
    description_ar: "كورتادو ناعم مع صوص الكراميل الذهبي ورغوة الحليب الغنية.",
    description_fr: "Cortado gourmand sublimé par un filet de caramel doré et mousse de lait.",
    price: 14,
    calories: 105,
    image_url: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_flat_white",
    name_en: "Flat White",
    name_ar: "فلات وايت",
    name_fr: "Flat White Artisanal",
    description_en: "Double ristretto shot layered with silky, glossy microfoam for velvety coffee texture.",
    description_ar: "دبل ريستريتو مع رغوة حليب ميكروفوم حريرية فاخرة.",
    description_fr: "Double dose de ristretto recouvert d'une micro-mousse de lait ultra soyeuse.",
    price: 17,
    calories: 130,
    image_url: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "sig_cold_white_brew",
    name_en: "Cold White Brew",
    name_ar: "برو أبيض بارد",
    name_fr: "Cold White Brew",
    description_en: "16-hour slow steeped cold brew coffee poured over creamy chilled milk.",
    description_ar: "قهوة كولد برو مقطرة ببطء لمدة 16 ساعة مع حليب بارد كريمي.",
    description_fr: "Café infusé à froid pendant 16h servi sur un lit de lait frais onctueux.",
    price: 22,
    calories: 90,
    image_url: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "sig_matcha_latte",
    name_en: "Matcha Green Tea Latte (Hot & Iced)",
    name_ar: "ماتشا الشاي الأخضر لاتيه",
    name_fr: "Latte Matcha Thé Vert (Chaud ou Glacé)",
    description_en: "Premium ceremonial matcha whisked with silky steamed or iced milk.",
    description_ar: "شاي ماتشا ياباني فاخر محضر مع الحليب المبخر الساخن أو المثلج المنعش.",
    description_fr: "Matcha cérémonial japonais fouetté avec du lait chaud velouté ou frappé sur glace.",
    price: 21,
    calories: 160,
    image_url: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 5. BOBA TEAS (3 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "boba_tiger",
    name_en: "Tiger Boba Tea",
    name_ar: "شاي بوبا تايجر",
    name_fr: "Tiger Boba Milk Tea",
    description_en: "Brown sugar tiger stripes, black milk tea, and chewy sweet tapioca pearls.",
    description_ar: "شاي الحليب مع خطوط سكر القصب البني وكرات التابيوكا اللذيذة.",
    description_fr: "Thé au lait rayé au sucre brun caramélisé et perles de tapioca moelleuses.",
    price: 25,
    calories: 380,
    image_url: "https://images.unsplash.com/photo-1558857563-b37cf5a4f780?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "boba_thai",
    name_en: "Thai Boba Tea",
    name_ar: "شاي بوبا التايلاندي",
    name_fr: "Thai Boba Tea",
    description_en: "Authentic spiced orange Thai iced tea with sweet condensed milk and bouncy boba.",
    description_ar: "شاي تايلاندي تقليدي متبل مع الحليب المكثف المحلى ولآلئ البوبا.",
    description_fr: "Véritable thé thaïlandais aux épices douces, lait concentré et perles boba.",
    price: 25,
    calories: 360,
    image_url: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "tea",
    item_id: "boba_matcha",
    name_en: "Matcha Boba Tea",
    name_ar: "شاي بوبا ماتشا",
    name_fr: "Matcha Boba Tea",
    description_en: "Vibrant emerald matcha latte paired with warm brown sugar tapioca pearls.",
    description_ar: "شاي ماتشا لاتيه الأخضر الفاخر مع كرات التابيوكا اللذيذة.",
    description_fr: "Latte au matcha émeraude associé aux perles de tapioca chaudes au sucre brun.",
    price: 25,
    calories: 340,
    image_url: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 6. ENERGY DRINKS (5 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_original",
    name_en: "Red Bull Energy Drink (Original)",
    name_ar: "ريد بُل مشروب طاقة الأصلي",
    name_fr: "Red Bull Energy Drink Original (250ml)",
    description_en: "The world-famous classic energy drink gives wiiings.",
    description_ar: "مشروب الطاقة الشهير يمنحك جوانح.",
    description_fr: "La boisson énergisante culte qui donne des aiiiles (250ml).",
    price: 19,
    calories: 110,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_sugar_free",
    name_en: "Red Bull Sugar Free",
    name_ar: "ريد بُل خالي من السكر",
    name_fr: "Red Bull Sans Sucres (250ml)",
    description_en: "Zero calories and zero sugars with the full energizing kick.",
    description_ar: "خالي من السكر وخالي من السعرات الحرارية بنفس الطاقة المنعشة.",
    description_fr: "Zéro sucre, zéro calorie, même énergie revitalisante.",
    price: 19,
    calories: 5,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_watermelon",
    name_en: "Red Bull Watermelon (Red Edition)",
    name_ar: "ريد بُل بالبطيخ",
    name_fr: "Red Bull Pastèque (Red Edition)",
    description_en: "Crisp, refreshing taste of ripe summer watermelon with Red Bull energy.",
    description_ar: "نكهة البطيخ الصيفي المنعشة مع طاقة ريد بل.",
    description_fr: "Saveur estivale rafraîchissante de pastèque juteuse.",
    price: 19,
    calories: 115,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_coconut_berry",
    name_en: "Red Bull Coconut & Berry (White Edition)",
    name_ar: "ريد بُل بجوز الهند والتوت",
    name_fr: "Red Bull Coco & Baies (White Edition)",
    description_en: "Exotic blend of creamy coconut and sweet mixed berries.",
    description_ar: "مزيج استوائي لذيذ بين جوز الهند والتوت البري.",
    description_fr: "Mélange exotique gourmand de noix de coco et baies sauvages.",
    price: 19,
    calories: 115,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "combos",
    item_id: "redbull_blueberry",
    name_en: "Red Bull Blueberry (Blue Edition)",
    name_ar: "ريد بُل بالتوت الأزرق",
    name_fr: "Red Bull Myrtille (Blue Edition)",
    description_en: "Sweet and fruity blueberry flavor that energizes your day.",
    description_ar: "طعم التوت الأزرق اللذيذ المنعش مع طاقة ريد بل.",
    description_fr: "Arôme fruité et gourmand de myrtilles sauvages.",
    price: 19,
    calories: 115,
    image_url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 7. RED BULL MOJITOS (3 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "redbull_mojito_blue_lagoon",
    name_en: "Red Bull Blue Lagoon Mojito",
    name_ar: "ريد بُل بلو لاجون موهيتو",
    name_fr: "Mojito Red Bull Blue Lagoon",
    description_en: "Blue curacao, fresh lime, mint leaves, energized with chilled Red Bull.",
    description_ar: "بلو كوراساو مع الليمون والنعناع ومشروب ريد بُل المثلج.",
    description_fr: "Curaçao bleu, citron vert, menthe fraîche pilée et canette Red Bull.",
    price: 27,
    calories: 170,
    image_url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "redbull_mojito_strawberry",
    name_en: "Red Bull Strawberry Mojito",
    name_ar: "ريد بُل بالفراولة موهيتو",
    name_fr: "Mojito Red Bull Fraise",
    description_en: "Fresh crushed strawberries, mint, lime, and energized Red Bull splash.",
    description_ar: "فراولة طبيعية مهروسة مع النعناع والليمون ومشروب ريد بل المنعش.",
    description_fr: "Fraises écrasées, menthe fraîche, citron vert et Red Bull glacé.",
    price: 27,
    calories: 180,
    image_url: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "mojitos",
    item_id: "redbull_mojito_passion_fruit",
    name_en: "Red Bull Passion Fruit Mojito",
    name_ar: "ريد بُل بفاكهة الماراكوجا موهيتو",
    name_fr: "Mojito Red Bull Passion",
    description_en: "Tropical passion fruit pulp, crushed ice, mint, topped with crisp Red Bull.",
    description_ar: "لب الماراكوجا الاستوائية مع الثلج المجروش والنعناع ومشروب ريد بل.",
    description_fr: "Pulpe de fruit de la passion, glace pilée, menthe et boost Red Bull.",
    price: 27,
    calories: 175,
    image_url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 8. JUICES (4 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "juice_apple",
    name_en: "Apple Juice",
    name_ar: "عصير تفاح طبيعي",
    name_fr: "Jus de Pomme 250ml",
    description_en: "100% pure clear refreshing apple juice.",
    description_ar: "عصير تفاح نقي 100% ومنعش.",
    description_fr: "Pur jus de pomme limpide et désaltérant.",
    price: 6,
    calories: 110,
    image_url: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "juice_mango",
    name_en: "Mango Juice",
    name_ar: "عصير مانجو",
    name_fr: "Jus de Mangue 250ml",
    description_en: "Rich and sweet tropical mango juice.",
    description_ar: "عصير مانجو استوائي غني ولذيذ.",
    description_fr: "Jus de mangue onctueux et gorgé de soleil.",
    price: 6,
    calories: 130,
    image_url: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "juice_orange",
    name_en: "Orange Juice",
    name_ar: "عصير البرتقال",
    name_fr: "Jus d'Orange 250ml",
    description_en: "Refreshing citrus orange juice packed with vitamin C.",
    description_ar: "عصير برتقال طبيعي غني بفيتامين سي.",
    description_fr: "Jus d'orange rafraîchissant gorgé de vitamine C.",
    price: 6,
    calories: 110,
    image_url: "https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "juice_pineapple",
    name_en: "Pineapple Juice",
    name_ar: "عصير أناناس",
    name_fr: "Jus d'Ananas 250ml",
    description_en: "Tropical sweet and tangy pineapple juice.",
    description_ar: "عصير أناناس منعش وطبيعي.",
    description_fr: "Pur jus d'ananas fruité et acidulé.",
    price: 6,
    calories: 120,
    image_url: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 9. WATERS (3 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "water_highland_sparkling",
    name_en: "Highland Sparkling Water",
    name_ar: "مياه هايلاند الغازية",
    name_fr: "Eau Pétillante Highland 330ml",
    description_en: "Pure Scottish highland sparkling mineral water.",
    description_ar: "مياه معدنية فوارة نقية من المرتفعات الاسكتلندية.",
    description_fr: "Eau minérale naturellement gazeuse des Highlands.",
    price: 5,
    calories: 0,
    image_url: "https://images.unsplash.com/photo-1559839914-ba2a0f8eb8fa?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "water_fiji",
    name_en: "Fiji Water",
    name_ar: "مياه فيجي الطبيعية",
    name_fr: "Eau Minérale Fiji 330ml",
    description_en: "Pristine artesian natural mineral water from the islands of Fiji.",
    description_ar: "مياه طبيعية نقية مستخرجة من جزر فيجي الاستوائية.",
    description_fr: "Eau artésienne pure issue des îles tropicales de Fidji.",
    price: 6,
    calories: 0,
    image_url: "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "water_highland_still",
    name_en: "Highland Still Mineral Water",
    name_ar: "مياه هايلاند الطبيعية المعدنية",
    name_fr: "Eau Plate Highland 500ml",
    description_en: "Premium Scottish still mineral water.",
    description_ar: "مياه معدنية طبيعية نقية من المرتفعات الاسكتلندية.",
    description_fr: "Eau minérale naturelle plate pure des Highlands d'Écosse.",
    price: 7,
    calories: 0,
    image_url: "https://images.unsplash.com/photo-1559839914-ba2a0f8eb8fa?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },

  // ================= 10. CHIPS / PATATINA (3 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chips_patatina_original",
    name_en: "Patatina Original Salted Chips",
    name_ar: "رقائق بطاطس باتاتينا الأصلية",
    name_fr: "Chips Patatina Classica",
    description_en: "Golden crispy Italian potato chips lightly sprinkled with sea salt.",
    description_ar: "رقائق بطاطس إيطالية ذهبية مقرمشة ومملحة بملح البحر.",
    description_fr: "Chips italiennes dorées et croustillantes au sel de mer.",
    price: 8,
    calories: 220,
    image_url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chips_patatina_paprika",
    name_en: "Patatina Paprika Chips",
    name_ar: "رقائق بطاطس باتاتينا بالبابريكا",
    name_fr: "Chips Patatina Paprika",
    description_en: "Artisan kettle-cooked chips seasoned with smoky sweet paprika.",
    description_ar: "رقائق بطاطس مقرمشة متبلة بنكهة البابريكا المدخنة اللذيذة.",
    description_fr: "Chips artisanales parfumées au paprika doux et fumé.",
    price: 8,
    calories: 220,
    image_url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "bakery",
    item_id: "chips_patatina_lemon_basil",
    name_en: "Patatina Lemon & Basil Chips",
    name_ar: "رقائق بطاطس باتاتينا بالليمون والريحان",
    name_fr: "Chips Patatina Citron & Basilic",
    description_en: "Mediterranean crunchy chips with zesty lemon essence and fragrant basil.",
    description_ar: "رقائق بطاطس بنكهة الليمون المنعش والريحان العطري المتوسطي.",
    description_fr: "Chips méditerranéennes croustillantes au citron zeste et basilic frais.",
    price: 8,
    calories: 220,
    image_url: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 11. CHOCOLATES / RITTER SPORT (4 items) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "chocolate_ritter_alpine_milk",
    name_en: "Ritter Sport Alpine Milk Chocolate",
    name_ar: "شوكولاتة حليب الألب ريتر سبورت",
    name_fr: "Ritter Sport Chocolat au Lait des Alpes 100g",
    description_en: "100% pure alpine milk chocolate with rich velvety cocoa notes.",
    description_ar: "شوكولاتة الحليب الألبية الكلاسيكية الفاخرة 100 جرام.",
    description_fr: "Chocolat pur au lait des Alpes crémeux et fondant (100g).",
    price: 15,
    calories: 540,
    image_url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "chocolate_ritter_dark_70",
    name_en: "Ritter Sport Dark Chocolate 70%",
    name_ar: "شوكولاتة داكنة 70% ريتر سبورت",
    name_fr: "Ritter Sport Chocolat Noir 70% 100g",
    description_en: "Intense 70% cocoa dark chocolate from fine roasted beans.",
    description_ar: "شوكولاتة داكنة غنية بنسبة 70% كاكاو لنكهة قوية وفاخرة.",
    description_fr: "Chocolat noir intense 70% de cacao aux arômes corsés.",
    price: 15,
    calories: 560,
    image_url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "chocolate_ritter_marzipan",
    name_en: "Ritter Sport Dark Chocolate with Marzipan",
    name_ar: "شوكولاتة داكنة مع مرزبان ريتر سبورت",
    name_fr: "Ritter Sport Noir Massepain 100g",
    description_en: "Dark chocolate filled with succulent Californian sweet almond marzipan.",
    description_ar: "شوكولاتة داكنة محشوة بحلوى المرزبان الفاخرة باللوز الحلو.",
    description_fr: "Chocolat noir noble garni d'un cœur fondant de massepain aux amandes.",
    price: 15,
    calories: 490,
    image_url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 0
  },
  {
    instance_name: "bos_cafe_aspire",
    category: "cakes",
    item_id: "chocolate_ritter_caramel_mousse",
    name_en: "Ritter Sport Caramel Mousse",
    name_ar: "موس الكراميل ريتر سبورت",
    name_fr: "Ritter Sport Mousse Caramel 100g",
    description_en: "Milk chocolate filled with whipped caramel mousse and roasted almond bits.",
    description_ar: "شوكولاتة بالحليب محشوة بموس الكراميل المخفوق ورقائق اللوز.",
    description_fr: "Chocolat au lait garni d'une mousse fouettée au caramel beurre et éclats d'amandes.",
    price: 15,
    calories: 570,
    image_url: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  },

  // ================= 12. MT. APO BEANS (1 item) =================
  {
    instance_name: "bos_cafe_aspire",
    category: "coffee",
    item_id: "beans_mt_apo_250g",
    name_en: "Mt. Apo Single Origin Specialty Coffee (250g)",
    name_ar: "حبوب بن جبل آبو الفلبيني الفاخرة",
    name_fr: "Café de Spécialité Mt. Apo 250g",
    description_en: "Bo's Coffee signature 100% Arabica beans harvested from Mt. Apo volcanic highlands, notes of sweet sugarcane and roasted hazelnut.",
    description_ar: "حبوب بن أرابيكا 100% المميزة من مرتفعات جبل آبو البركانية بنكهات السكر البني والبندق المحمص.",
    description_fr: "Grains 100% Arabica signature récoltés sur les hautes terres du mont Apo, notes de canne à sucre et noisette grillée.",
    price: 65,
    calories: 0,
    image_url: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80",
    is_available: 1,
    is_popular: 1
  }
];

function postBatch(items, startIndex, batchSize) {
  const batch = items.slice(startIndex, startIndex + batchSize);
  if (batch.length === 0) {
    console.log(`\n🎉 Tous les articles supplémentaires (${items.length}) ont été insérés avec succès !`);
    return;
  }

  const postData = JSON.stringify(batch);

  const options = {
    hostname: NOCODB_HOST,
    port: NOCODB_PORT,
    path: `/api/v2/tables/${TABLE_ID}/records`,
    method: 'POST',
    headers: {
      'xc-token': NOCODB_TOKEN,
      'Content-Type': 'application/json',
      'Content-Length': Buffer.byteLength(postData)
    }
  };

  const req = http.request(options, (res) => {
    let responseBody = '';
    res.on('data', (chunk) => { responseBody += chunk; });
    res.on('end', () => {
      console.log(`Lot ${startIndex + 1} à ${startIndex + batch.length}: Status ${res.statusCode}`);
      if (res.statusCode >= 200 && res.statusCode < 300) {
        postBatch(items, startIndex + batchSize, batchSize);
      } else {
        console.error(`Erreur sur le lot :`, responseBody);
      }
    });
  });

  req.on('error', (e) => {
    console.error(`Problème requête HTTP : ${e.message}`);
  });

  req.write(postData);
  req.end();
}

console.log(`Insertion de ${newItems.length} nouveaux articles pour bos_cafe_aspire...`);
postBatch(newItems, 0, 25);
